### ISSUE TITLE
Suggestion - 1.16.3 support

### ISSUE THREAD

**Issue by IanuReeves** [Draylar/better-dropped-items#5]
plEASE add 1.16.3 support i am doing an "all the mods" thing for fabric-client-side mods and I want to give my friend it so... i can.

**Comment by egeesin** [comment]
Have you tried to open with it? The mod is already 1.16.3 compatible, issue should be closed.

**Comment by minecraftDigi101** [comment]
i will check again and write back if it is successfull;

**Comment by IanuReeves** [comment]
it isn't 1.16.3 tho, it's 1.16.2

**Comment by Draylar** [comment]
1.16.3 was a very small update; the latest jar should work on it despite being labeled for 1.16.2. If you still get a crash after trying, please post it to [hastebin](https://hastebin.com/) and send the link here.

**Comment by IanuReeves** [comment]
oh ok thanks :)

**Comment by IanuReeves** [comment]
can that kinda rule work with stuff like the reauth mod?

**Comment by Draylar** [comment]
You will have to test it and see; whether it works depends on what changed between versions, and what the mod touches. Smaller mods like these are less likely to break because stuff like item rendering isn't changed all that often.

_Most_ mods should work going from 1.16.2 to 1.16.3. Some mods hard depend on a specific version (eg. `1.16.2`) because the author forgets to add the `>=` sign before the version; if this happens, you'll get a popup window saying something like `mod xyz depends on Minecraft 1.16.2, but 1.16.3 is present!` If the mod actually doesn't work on that version, you will get a full crash log, which you should send to the mod's issue tracker through hastebin.

edit: and just to clarify, nothing bad will ever happen if you try to load your game with older versions of mods (like a 1.16.2 mod on 1.16.3) and it fails, especially with client-only mods. Might as well give it a shot.

**Comment by IanuReeves** [comment]
ok thank you
